require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "db/migrate/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "db/migrate/**/*"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/graphql/**/*"

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
