default: &default
  adapter: postgis
  encoding: unicode
  schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_sandbox_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: rails_api_sandbox_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: rails_api_sandbox_production
  url: <%= ENV['DATABASE_URL'] %>
